# Generated by Django 5.2 on 2025-04-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=100)),
                ('proddesc', models.TextField()),
                ('prodprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prodrating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prodimage', models.ImageField(upload_to='images/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bookapp.categories')),
            ],
        ),
    ]
