# Generated by Django 5.2 on 2025-05-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0003_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=100)),
                ('custaddress', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andra Pradesh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra')], max_length=2)),
                ('custcontact', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
