# Generated by Django 5.2 on 2025-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0006_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delete_details',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
