# Generated by Django 5.2 on 2025-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0007_products_delete_details_products_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bookorder_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
